apiVersion: v1
kind: PersistentVolume
metadata:
  name: karmada-dashboard-etcd-pv
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/etcd"
